language: go
rvm:
  - 1.9.3
install:
  - go get github.com/shaoshing/gotest
  - go get github.com/shaoshing/train
  - go get github.com/shaoshing/train/interpreter
  - gem in sass --pre
  - gem in coffee-script
script:
  cd $GOPATH/src/github.com/shaoshing/train
  ./test_all.sh
